#!/usr/bin/env python

# owtemp.py. This script displays the measured temperature in C in the terminal window. 

# The update interval is based on the variable on line 22: time.sleep() 

import time
import os

# The file name and path uses the unique id generated by the onboad ROM on the sensor. 

file_name=os.path.join("/","mnt","1wire","28.AF6A9E050000","temperature")

# The code isn't actually 'opening' and then 'closing' a file as the syntax suggests

# The 'file' is actually a path to the Raspberry Pi's ROM

while 1:
    file_object=open(file_name,'r')  
    line=file_object.read()
    print(line+'C')
    time.sleep(5) 
    file_object.close()
